version: "2"
services:
  t-server:
    container_name: t-server
    restart: always
    build: ./t-server
    ports:
      - "5500:8080"
    depends_on:
      - mongo
    volumes:
      - ./t-server:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  t-ui:
    container_name: t-ui
    restart: always
    build: ./t-ui
    ports:
      - "4000:3000"
    volumes:
      - ./t-ui:/usr/src/app
